---
- hosts: pi
  remote_user: pi

  tasks:
    - name: Stops old release
      command: /home/pi/apps/dhcp_watcher/bin/dhcp_watcher stop
      ignore_errors: yes

    - name: Clean up app dir
      shell: /bin/rm -rf /home/pi/apps/dhcp_watcher/*
      ignore_errors: yes

    - name: Create Apps directory to deploy
      ansible.builtin.file:
        path: /home/pi/apps/dhcp_watcher
        state: directory

    - name: Deploy app to raspberry pi
      ansible.builtin.unarchive:
        src: ../dhcp_watcher-0.1.0.tar.gz
        dest: /home/pi/apps/dhcp_watcher

    - name: Start server
      command: /home/pi/apps/dhcp_watcher/bin/dhcp_watcher daemon
      register: result
      failed_when: result.rc != 0